https://www.kaggle.com/krishanudb/pytorch-tutorial-for-beginners  

In [1]:
import torch

In [2]:
torch.__version__

'1.7.1+cpu'

In [7]:
torch.empty([5, 3])

tensor([[3.7329e-11, 4.5859e-41, 8.1437e-37],
        [0.0000e+00, 1.5568e-19, 4.5859e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
torch.empty(5, 3)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 8.1131e-37, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.9703e-37],
        [0.0000e+00, 7.9703e-37, 0.0000e+00],
        [7.9704e-37, 0.0000e+00, 0.0000e+00]])

In [9]:
torch.rand(5, 4)

tensor([[0.1168, 0.7177, 0.2310, 0.8503],
        [0.7604, 0.4255, 0.1938, 0.8721],
        [0.5883, 0.8031, 0.7286, 0.4074],
        [0.8950, 0.0518, 0.4779, 0.5699],
        [0.2897, 0.3655, 0.5240, 0.1734]])

In [10]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [11]:
torch.tensor([5.09, 3])

tensor([5.0900, 3.0000])

In [14]:
z = torch.tensor([5.09, 3])
c = torch.randn_like(z, dtype=torch.float32)

In [16]:
c = c.new_ones(5, 6, dtype=torch.double)
c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=torch.float64)

In [21]:
c.size()

torch.Size([5, 6])

In [23]:
d = torch.randn(5, 6, dtype=torch.double)
c + d

tensor([[ 2.5460,  2.0187,  1.0938,  1.8710,  1.2305,  2.9570],
        [ 0.9437,  0.1476, -0.8965,  0.6347,  1.9060,  1.7669],
        [ 1.3527,  1.3946,  0.8661,  1.5366,  1.2078,  1.4986],
        [ 1.5331, -0.1550,  2.4074, -0.1772,  0.9237,  0.8872],
        [ 0.6743,  0.5181,  0.3173,  0.2909,  0.1339,  0.3405]],
       dtype=torch.float64)

In [26]:
e = torch.randn(5, 6, dtype = torch.float)
c + e

tensor([[ 1.9538,  0.7757, -1.0642, -0.4111,  0.8674,  2.2285],
        [ 1.5915,  0.9738,  0.5108, -0.2370,  0.7437,  3.7423],
        [ 0.4352,  1.3081,  0.6201,  1.0112,  0.5462,  1.7255],
        [ 1.3624, -0.2190,  0.2069,  2.2815,  0.3186,  0.2639],
        [ 1.2136,  1.4742,  1.2075, -0.0397,  0.7701,  1.8023]],
       dtype=torch.float64)

In [27]:
torch.add(c, d)

tensor([[ 2.5460,  2.0187,  1.0938,  1.8710,  1.2305,  2.9570],
        [ 0.9437,  0.1476, -0.8965,  0.6347,  1.9060,  1.7669],
        [ 1.3527,  1.3946,  0.8661,  1.5366,  1.2078,  1.4986],
        [ 1.5331, -0.1550,  2.4074, -0.1772,  0.9237,  0.8872],
        [ 0.6743,  0.5181,  0.3173,  0.2909,  0.1339,  0.3405]],
       dtype=torch.float64)

In [29]:
result = torch.empty(5, 6, dtype=torch.double)
torch.add(c, d, out=result)
result

tensor([[ 2.5460,  2.0187,  1.0938,  1.8710,  1.2305,  2.9570],
        [ 0.9437,  0.1476, -0.8965,  0.6347,  1.9060,  1.7669],
        [ 1.3527,  1.3946,  0.8661,  1.5366,  1.2078,  1.4986],
        [ 1.5331, -0.1550,  2.4074, -0.1772,  0.9237,  0.8872],
        [ 0.6743,  0.5181,  0.3173,  0.2909,  0.1339,  0.3405]],
       dtype=torch.float64)

In [30]:
e = d
e.add_(c)
e

tensor([[ 2.5460,  2.0187,  1.0938,  1.8710,  1.2305,  2.9570],
        [ 0.9437,  0.1476, -0.8965,  0.6347,  1.9060,  1.7669],
        [ 1.3527,  1.3946,  0.8661,  1.5366,  1.2078,  1.4986],
        [ 1.5331, -0.1550,  2.4074, -0.1772,  0.9237,  0.8872],
        [ 0.6743,  0.5181,  0.3173,  0.2909,  0.1339,  0.3405]],
       dtype=torch.float64)

In [31]:
e[:, 1]

tensor([ 2.0187,  0.1476,  1.3946, -0.1550,  0.5181], dtype=torch.float64)

In [33]:
x = torch.randn(4, 5)
y = x.view(20)
z = x.view(-1, 2, 2)
x.size(), y.size(), z.size()

(torch.Size([4, 5]), torch.Size([20]), torch.Size([5, 2, 2]))

In [34]:
e.numpy()

array([[ 2.54595536,  2.01871443,  1.09377593,  1.87098549,  1.23047205,
         2.95698416],
       [ 0.94372107,  0.1475954 , -0.89646244,  0.6346826 ,  1.90600761,
         1.76689964],
       [ 1.352696  ,  1.39463573,  0.86611195,  1.53655923,  1.207821  ,
         1.49858627],
       [ 1.53313134, -0.15501297,  2.407384  , -0.1771679 ,  0.92374614,
         0.88723432],
       [ 0.67425869,  0.51808215,  0.31726656,  0.29090417,  0.13387351,
         0.34046252]])

In [37]:
a = torch.ones(2, 3)
b = a.numpy()
print(b)
a = a.add_(1)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[2., 2., 2.],
        [2., 2., 2.]])
[[2. 2. 2.]
 [2. 2. 2.]]


In [38]:
import numpy as np
a = np.ones((5, 2))
b = torch.from_numpy(a) ## This is the command
print(b)
np.add(a, 3, out = a)
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]
tensor([[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]], dtype=torch.float64)


In [39]:
x = torch.ones(2, 3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [40]:
y = x + 2
print(y)

tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


In [41]:
print(y.grad_fn)

In [42]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [43]:
out.backward()

In [44]:
print(x.grad)

tensor([[3., 3., 3.],
        [3., 3., 3.]])
